# -*- coding: utf-8 -*-
"""Car_Purchasing_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAP6TaQTqHeCGa8yQCLIydJM5-_r8JbV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt
import seaborn as sns

car = pd.read_csv('Car_Purchasing_Data.csv',encoding='ISO-8859-1')

car

sns.pairplot(car)

X = car.drop(['Customer Name','Customer e-mail','Country','Car Purchase Amount'],axis=1)

X.shape

y = car['Car Purchase Amount']

from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
X = Scaler.fit_transform(X)

y=y.values.reshape(-1,1)

y = Scaler.fit_transform(y)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

X_train.shape

import tensorflow as tf

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(units=30,activation='relu'))

model.add(tf.keras.layers.Dense(units=30,activation='relu'))

model.add(tf.keras.layers.Dense(units=1,activation='linear'))

model.compile (optimizer='adam',loss='mean_squared_error')

model.fit(X_train,y_train,epochs=50,batch_size=25,verbose=1,validation_split=0.02)

X_test = np.array([[1,57,59000,5300,56000]])
y_predict = model.predict(X_test)

print(y_predict)
[[34282.754]]